Added strimzi installation.
stakater-lab/nordmart-dev-tools pull request #18
Opened 2020-01-20 18:38 UTC by oleksii-kondratiuk

2020-01-22 09:34 UTC, ahmedwaleedmalik requested changes
I'd suggest if we could go with `kafka-operator` instead of `strimzi` everywhere. If you think that's appropriate please make the change

2020-01-22 09:34 UTC, ahmedwaleedmalik commented on tools-istio/strimzi.yaml
> +  name: nordmart-dev-strimzi
`nordmart-dev-strimzi-kafka-operator`

2020-01-22 09:34 UTC, ahmedwaleedmalik commented on tools-istio/strimzi.yaml
> +  releaseName: nordmart-dev-strimzi
`nordmart-dev-strimzi-kafka-operator`

2020-01-23 07:45 UTC, oleksii-kondratiuk commented on tools-istio/strimzi.yaml
> +  name: nordmart-dev-strimzi
Agree on the naming, changed.

2020-01-23 07:45 UTC, oleksii-kondratiuk commented on tools-istio/strimzi.yaml
> +  releaseName: nordmart-dev-strimzi
Agree on the naming, changed.

2020-01-23 11:09 UTC, ahmedwaleedmalik commented on tools-istio/strimzi.yaml
> +  name: nordmart-dev-strimzi
Thanks

2020-01-23 11:11 UTC, ahmedwaleedmalik approved these changes

2020-01-23 11:12 UTC, merged